# duktape — Embeddable JavaScript engine
#
# BLFS

[package]
name = "duktape"
version = "2.7.0"
description = "duktape — Embeddable JavaScript engine"
license = "MIT"
groups = ["desktop", "libs"]
release = 1
arch = "x86_64"

[source]
url = "https://duktape.org/duktape-2.7.0.tar.xz"
sha256 = "90f8d2fa8b5567c6899830ddef2c03f3c27960b11aca222fa17aa7ac613c2890"
patches = []

[depends]
runtime = ["glibc"]
build = ["gcc", "make", "pkgconf"]

[build]
pre_build = ""
configure = ""
make = "make -f Makefile.sharedlibrary"
check = ""
install = "make -f Makefile.sharedlibrary INSTALL_PREFIX=$PKG/usr install"
post_install = ""

[security]
hardening = ["pie", "fullrelro", "fortify", "stackprotector", "bindnow"]
cflags = "-O2 -pipe"
ldflags = "-Wl,--as-needed"
