[package]
name = "libxdmcp"
version = "1.1.5"
description = "X Display Manager Control Protocol library"
license = "MIT"
groups = ["desktop"]
release = 1
arch = "x86_64"

[source]
url = "https://www.x.org/releases/individual/lib/libXdmcp-1.1.5.tar.xz"
sha256 = "d8a5222828c3adab70adf69a5583f1d32eb5ece04304f7f8392b6a353aa2228c"
patches = []

[depends]
runtime = ["xorgproto"]
build = ["autoconf", "automake", "libtool"]
optional = []

[build]
pre_build = ""
configure = "./configure --prefix=/usr"
make = "make -j$(nproc)"
check = ""
install = "make DESTDIR=$PKG install"

[security]
hardening = ["pie", "fullrelro", "fortify", "stackprotector", "bindnow"]
cflags = "-O2 -pipe"
ldflags = "-Wl,--as-needed"
